# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180629_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Log',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='cantidad_vendida',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo_p',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='unidades',
            new_name='existencia',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='proveedor',
        ),
    ]
